* **Opcje konfiguracyjne**

  W tej części omówione są wszystkie konfiguracje pakietów zawartych w dystrybucji
  Symfony Standard Edition. Konfiguracja pakietów zewnętrznych powinna być omówiona
  w dokumentacji tych pakietów (i tak jest z reguły).  

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* :doc:`Konfiguracja Kernela (np. AppKernel) </reference/configuration/kernel>`

* **Formularze i walidacja**

  * :doc:`/reference/forms/types`
  * :doc:`/reference/constraints`
  * :doc:`/reference/forms/twig_reference`

* :doc:`Informator rozszerzeń Twig (formularz, filtry, znaczniki itd.) </reference/twig_reference>`

* **Pozostałe**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/events`
  * :doc:`/reference/requirements`
