Kluczowe pakiety
~~~~~~~~~~~~~~~~

Większość pakietów Symfony CMF dostarcza jakąś funkcjonalność, integruje bibliotekę
lub wprowadza zupełnie nową koncepcję.

* :doc:`block/index`

  * :doc:`block/introduction`
  * :doc:`block/types`
  * :doc:`block/create_your_own_blocks`
  * :doc:`block/cache`
  * :doc:`block/relation_to_sonata_block_bundle`

* :doc:`core/index`

  * :doc:`core/introduction`
  * :doc:`core/publish_workflow`
  * :doc:`core/dependency_injection_tags`
  * :doc:`core/templating`
  * :doc:`core/persistence`
  * :doc:`core/forms`

* :doc:`create/index`

  * :doc:`create/introduction`
  * :doc:`create/other-editors`
  * :doc:`create/developing-hallo`

* :doc:`media/index`

  * :doc:`media/introduction`
  * :doc:`media/form_types`
  * :doc:`media/adapters/index`

* :doc:`menu/index`

  * :doc:`menu/introduction`
  * :doc:`menu/menu_documents`
  * :doc:`menu/menu_factory`
  * :doc:`menu/menu_provider`
  * :doc:`menu/voters`
  * :doc:`menu/sonata_admin`

* :doc:`routing/index`

  * :doc:`routing/introduction`
  * :doc:`routing/dynamic`
  * :doc:`routing/dynamic_customize`

* :doc:`routing_auto/index`

  * :doc:`routing_auto/introduction`
  * :doc:`routing_auto/providers`
  * :doc:`routing_auto/exists_actions`
  * :doc:`routing_auto/not_exists_actions`
  * :doc:`routing_auto/customization`

* :doc:`search/index`

  * :doc:`search/introduction`

* :doc:`seo/index`

  * :doc:`seo/introduction`
  * :doc:`seo/seo_aware`
  * :doc:`seo/extractors`

* :doc:`tree_browser/index`

  * :doc:`tree_browser/introduction`

Pakiety prezentacyjne
~~~~~~~~~~~~~~~~~~~~~

Inne pakiety dostarczają przykładów o zastosowaniu kluczowych pakietów. Pokazują
różne sposoby implementowania koncepcji. Można wykorzystywać te pakiety we własnych
projektach, ale można też zaczerpnąć z tych pakietów różne pomysły do stworzenia
własnych pakietów opartych na pakietach kluczowych.

* **BlogBundle**

  * :doc:`blog`

* :doc:`content/index`

  * :doc:`content/introduction`

* :doc:`simple_cms/index`

  * :doc:`simple_cms/introduction`
  * :doc:`simple_cms/multilang`
  * :doc:`simple_cms/rendering`
  * :doc:`simple_cms/extending_page_class`

Pakiety rozwojowe
~~~~~~~~~~~~~~~~~

Ponadto, zespół Symfony CMF utrzymuje kilka pakietów osób trzecich, które pomagają
w integracji koncepcji PHPCR w frameworku Symfony.

* :doc:`phpcr_odm/index`

  * :doc:`phpcr_odm/introduction`
  * :doc:`phpcr_odm/events`
  * :doc:`phpcr_odm/forms`
  * :doc:`phpcr_odm/fixtures_initializers`
  * :doc:`phpcr_odm/multilang`
  * :doc:`phpcr_odm/multiple_sessions`

* SonataDoctrinePHPCRAdminBundle_

.. _SonataDoctrinePHPCRAdminBundle: http://sonata-project.org/bundles/doctrine-phpcr-admin/master/doc/index.html
